"""
Server-authoritative power-up (pickup) synchronization for XPilot Web.

The relay server (ws_server.py) owns all power-up state so that every
connected client sees identical pickups at identical locations:

* The server owns all spawn/respawn timers.
* Every power-up gets a unique ID assigned by the server.
* Pickup requests (collection) and bullet hits are validated by the
  server before they are applied.
* The server broadcasts spawn, pickup, damage and explosion events.
* The server periodically broadcasts an authoritative full-state
  snapshot that late-joiners receive immediately and that lets clients
  reconcile any mismatched state.

Clients never create, move or destroy power-ups on their own while the
server is authoritative; they render exactly what this module says.

The deterministic obstacle layout mirrors the map generated by
xpilot-web.html (seeded RNG) so server-chosen spawn positions are always
valid for every client.
"""

import math
import random

# ---------------------------------------------------------------------------
# World / map constants (must match xpilot-web.html)
# ---------------------------------------------------------------------------
WORLD_W = 3200
WORLD_H = 2400
MAP_SEED = 0x58506c74
FILL_SEED = 0x58506c74 ^ 0x9e3779b9

SPAWN_CX = WORLD_W / 2
SPAWN_CY = WORLD_H / 2
CLEAR_R = 380
MIN_SEP = 300
EDGE = 80

# ---------------------------------------------------------------------------
# Power-up definitions (mirror pickup-system.js / POWERUP_DEFS)
# ---------------------------------------------------------------------------
PICKUP_DEFS = {
    "shield": {
        "r": 10,
        "hp": 2,
        "respawn": 16,
        "blastRadius": 0,
        "respawnKind": None,
        "explosionDelay": 0,
    },
    "score_mult": {
        "r": 10,
        "hp": 1,
        "respawn": 15,
        "blastRadius": 0,
        "respawnKind": None,
        "explosionDelay": 0,
    },
    "fuel_cell": {
        "r": 12,
        "hp": 3,
        "respawn": 24,
        "blastRadius": 90,
        "respawnKind": "fuel_cell",
        "explosionDelay": 1.4,
    },
}
PICKUP_KINDS = list(PICKUP_DEFS.keys())

N_CUBES = 80
N_SHIELD_CUBES = 5
N_FUEL_CELLS = 7

# Collection respawn time range used by the client for picked-up cubes.
COLLECT_RESPAWN_MIN = 18
COLLECT_RESPAWN_RANGE = 8

# Distance (pickup radius + margin) within which a player may collect.
PICKUP_REACH = 10


# ---------------------------------------------------------------------------
# Seeded RNG (must match the client's mkRng/mkRng usage exactly)
# ---------------------------------------------------------------------------
def mk_rng(seed):
    seed &= 0xFFFFFFFF

    def rng():
        nonlocal seed
        seed = (1664525 * seed + 1013904223) & 0xFFFFFFFF
        return seed / 4294967296.0

    return rng


def wrap_delta(a, b, size):
    d = ((b - a) % size + size) % size
    if d > size / 2:
        d -= size
    return d


# ---------------------------------------------------------------------------
# Geometry helpers (mirror xpilot-web.html)
# ---------------------------------------------------------------------------
def point_in_poly(px, py, pts):
    inside = False
    n = len(pts)
    for i in range(n):
        j = i - 1
        xi, yi = pts[i]
        xj, yj = pts[j]
        if ((yi > py) != (yj > py)) and (px < (xj - xi) * (py - yi) / (yj - yi) + xi):
            inside = not inside
    return inside


def dist_sq_point_seg(px, py, ax, ay, bx, by):
    dx = bx - ax
    dy = by - ay
    len2 = dx * dx + dy * dy
    if len2 == 0:
        return math.hypot(px - ax, py - ay)
    t = max(0.0, min(1.0, ((px - ax) * dx + (py - ay) * dy) / len2))
    return math.hypot(px - (ax + t * dx), py - (ay + t * dy))


def circle_hits_obs(cx, cy, r, obs):
    dx = wrap_delta(obs["cx"], cx, WORLD_W)
    dy = wrap_delta(obs["cy"], cy, WORLD_H)
    if math.hypot(dx, dy) > obs["r"] + r + 10:
        return False
    tcx = obs["cx"] + dx
    tcy = obs["cy"] + dy
    if point_in_poly(tcx, tcy, obs["pts"]):
        return True
    pts = obs["pts"]
    for i in range(len(pts)):
        j = i - 1
        if dist_sq_point_seg(tcx, tcy, pts[j][0], pts[j][1], pts[i][0], pts[i][1]) < r:
            return True
    return False


def gen_blob_pts(cx, cy, base_r, n_pts, rand):
    angs = sorted((i / n_pts) * math.tau + (rand() - 0.5) * 0.55 for i in range(n_pts))
    pts = []
    for a in angs:
        r = base_r * (0.52 + 0.48 * rand())
        pts.append((cx + math.cos(a) * r, cy + math.sin(a) * r))
    return pts


def build_obstacles():
    """Deterministically generate the same obstacle map as the client."""
    map_rng = mk_rng(MAP_SEED)
    obs = []
    attempts = 0
    while len(obs) < 18 and attempts < 600:
        attempts += 1
        cx = 120 + map_rng() * (WORLD_W - 240)
        cy = 120 + map_rng() * (WORLD_H - 240)
        if math.hypot(cx - SPAWN_CX, cy - SPAWN_CY) < CLEAR_R:
            continue
        ok = True
        for o in obs:
            if math.hypot(cx - o["cx"], cy - o["cy"]) < MIN_SEP:
                ok = False
                break
        if not ok:
            continue
        base_r = 80 + map_rng() * 130
        n_pts = 8 + int(map_rng() * 6)
        obs.append({
            "pts": gen_blob_pts(cx, cy, base_r, n_pts, map_rng),
            "cx": cx,
            "cy": cy,
            "r": base_r * 1.15,
            "shade": int(map_rng() * 3),
        })

    fill_rng = mk_rng(FILL_SEED)
    for _ in range(12):
        g = 100
        best_d = -1.0
        best_x = 0
        best_y = 0
        gy = g / 2
        while gy < WORLD_H:
            gx = g / 2
            while gx < WORLD_W:
                d = 1e9
                for o in obs:
                    dx = wrap_delta(o["cx"], gx, WORLD_W)
                    dy = wrap_delta(o["cy"], gy, WORLD_H)
                    od = math.hypot(dx, dy) - o["r"]
                    if od < d:
                        d = od
                if d > best_d:
                    best_d = d
                    best_x = gx
                    best_y = gy
                gx += g
            gy += g
        if best_d < 360:
            break
        x = best_x + (fill_rng() - 0.5) * 120
        y = best_y + (fill_rng() - 0.5) * 120
        x = max(120, min(WORLD_W - 120, x))
        y = max(120, min(WORLD_H - 120, y))
        if math.hypot(x - SPAWN_CX, y - SPAWN_CY) < CLEAR_R:
            continue
        ok = True
        for o in obs:
            if math.hypot(x - o["cx"], y - o["cy"]) < MIN_SEP:
                ok = False
                break
        if not ok:
            continue
        base_r = 80 + fill_rng() * 130
        n_pts = 8 + int(fill_rng() * 6)
        obs.append({
            "pts": gen_blob_pts(x, y, base_r, n_pts, fill_rng),
            "cx": x,
            "cy": y,
            "r": base_r * 1.15,
            "shade": int(fill_rng() * 3),
        })
    return obs


# ---------------------------------------------------------------------------
# Server-authoritative power-up manager
# ---------------------------------------------------------------------------
class PowerUpManager:
    """Owns the authoritative power-up state for all connected clients."""

    def __init__(self, rng=None):
        self._rng = rng if rng is not None else random.random
        self.obstacles = build_obstacles()
        self._seq = 0
        self._snap_seq = 0
        self.pickups = {}
        self._spawn_initial()

    # -- helpers -------------------------------------------------------------
    def _next_id(self):
        self._seq += 1
        return "p%d" % self._seq

    def _rng_choice(self, items):
        idx = int(self._rng() * len(items))
        return items[min(idx, len(items) - 1)]

    def is_valid_pos(self, x, y, r):
        if x < EDGE + r or x > WORLD_W - EDGE - r:
            return False
        if y < EDGE + r or y > WORLD_H - EDGE - r:
            return False
        for obs in self.obstacles:
            if circle_hits_obs(x, y, r, obs):
                return False
        return True

    def find_position(self, r):
        for _ in range(250):
            x = EDGE + self._rng() * (WORLD_W - 2 * EDGE)
            y = EDGE + self._rng() * (WORLD_H - 2 * EDGE)
            if self.is_valid_pos(x, y, r):
                return x, y
        fx, fy = WORLD_W / 2, WORLD_H / 2
        if self.is_valid_pos(fx, fy, r):
            return fx, fy
        step = max(2, int(r * 2))
        for gx in range(EDGE, WORLD_W - EDGE, step):
            for gy in range(EDGE, WORLD_H - EDGE, step):
                if self.is_valid_pos(gx, gy, r):
                    return gx, gy
        return fx, fy

    # -- spawning ------------------------------------------------------------
    def _spawn_initial(self):
        kinds = []
        for _ in range(N_SHIELD_CUBES):
            kinds.append("shield")
        for _ in range(N_FUEL_CELLS):
            kinds.append("fuel_cell")
        for _ in range(N_CUBES - N_SHIELD_CUBES - N_FUEL_CELLS):
            kinds.append(self._rng_choice(PICKUP_KINDS))
        for kind in kinds:
            p = self._new_pickup(kind)
            self.pickups[p["id"]] = p

    def _new_pickup(self, kind):
        defn = PICKUP_DEFS[kind]
        x, y = self.find_position(defn["r"])
        return {
            "id": self._next_id(),
            "kind": kind,
            "x": x,
            "y": y,
            "r": defn["r"],
            "hp": defn["hp"],
            "maxHp": defn["hp"],
            "active": True,
            "respawnTimer": 0.0,
            "blastRadius": defn["blastRadius"],
            "respawnKind": defn["respawnKind"],
            "fuseActive": False,
            "fuseTimer": 0.0,
            "explosionDelay": defn["explosionDelay"],
        }

    def _respawn(self, p, events):
        kind = p["respawnKind"] or p["kind"]
        defn = PICKUP_DEFS[kind]
        p["kind"] = kind
        p["x"], p["y"] = self.find_position(defn["r"])
        p["r"] = defn["r"]
        p["hp"] = defn["hp"]
        p["maxHp"] = defn["hp"]
        p["active"] = True
        p["respawnTimer"] = 0.0
        p["blastRadius"] = defn["blastRadius"]
        p["respawnKind"] = defn["respawnKind"]
        p["fuseActive"] = False
        p["fuseTimer"] = 0.0
        p["explosionDelay"] = defn["explosionDelay"]
        events.append({"type": "pickup_spawned", "pickup": self._serialize(p)})

    # -- events --------------------------------------------------------------
    def try_collect(self, pickup_id, client_id, player_pos=None):
        """Validate and apply a pickup request. Returns an event or None."""
        p = self.pickups.get(pickup_id)
        if not p or not p["active"]:
            return None
        if p["kind"] == "fuel_cell" and p["fuseActive"]:
            return None
        if player_pos is not None:
            px, py = player_pos
            dx = wrap_delta(p["x"], px, WORLD_W)
            dy = wrap_delta(p["y"], py, WORLD_H)
            if math.hypot(dx, dy) > p["r"] + PICKUP_REACH:
                return None
        p["active"] = False
        p["respawnTimer"] = COLLECT_RESPAWN_MIN + self._rng() * COLLECT_RESPAWN_RANGE
        return {
            "type": "pickup_picked",
            "pickup": self._serialize(p),
            "by": client_id,
            "kind": p["kind"],
        }

    def apply_damage(self, pickup_id, damage=1, source=None):
        """Validate and apply bullet damage. Returns an event or None."""
        p = self.pickups.get(pickup_id)
        if not p or not p["active"]:
            return None
        if p["kind"] == "fuel_cell" and p["fuseActive"]:
            return None
        dmg = max(1, int(damage or 1))
        p["hp"] = max(0, p["hp"] - dmg)
        destroyed = p["hp"] <= 0
        primed = False
        if destroyed:
            if p["kind"] == "fuel_cell":
                p["active"] = False
                p["fuseActive"] = True
                p["fuseTimer"] = p["explosionDelay"]
                p["respawnTimer"] = 0.0
                primed = True
            else:
                p["active"] = False
                p["respawnTimer"] = PICKUP_DEFS[p["kind"]]["respawn"]
        return {
            "type": "pickup_damaged",
            "pickup": self._serialize(p),
            "by": source,
            "destroyed": destroyed,
            "primed": primed,
        }

    def tick(self, dt):
        """Advance timers; returns a list of events to broadcast."""
        events = []
        for p in self.pickups.values():
            if p["kind"] == "fuel_cell" and p["fuseActive"]:
                p["fuseTimer"] -= dt
                if p["fuseTimer"] <= 0:
                    defn = PICKUP_DEFS["fuel_cell"]
                    p["active"] = False
                    p["fuseActive"] = False
                    p["fuseTimer"] = 0.0
                    p["respawnTimer"] = defn["respawn"]
                    s = self._serialize(p)
                    events.append({
                        "type": "pickup_exploded",
                        "pickup": s,
                        "x": s["x"],
                        "y": s["y"],
                        "blastRadius": p["blastRadius"],
                    })
            if not p["active"] and p["respawnTimer"] > 0:
                p["respawnTimer"] -= dt
                if p["respawnTimer"] <= 0:
                    self._respawn(p, events)
        return events

    # -- snapshots -----------------------------------------------------------
    @staticmethod
    def _serialize(p):
        return {
            "id": p["id"],
            "kind": p["kind"],
            "x": round(p["x"], 4),
            "y": round(p["y"], 4),
            "r": p["r"],
            "hp": p["hp"],
            "maxHp": p["maxHp"],
            "active": bool(p["active"]),
            "respawnTimer": round(p["respawnTimer"], 3),
            "blastRadius": p["blastRadius"],
            "respawnKind": p["respawnKind"],
            "fuseActive": bool(p["fuseActive"]),
            "fuseTimer": round(p["fuseTimer"], 3),
            "explosionDelay": p["explosionDelay"],
        }

    def snapshot(self):
        return [self._serialize(p) for p in self.pickups.values()]

    def snapshot_message(self):
        self._snap_seq += 1
        return {
            "type": "pickup_state",
            "seq": self._snap_seq,
            "pickups": self.snapshot(),
        }
