apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ingressclass.yaml
  - cluster-issuers.yaml
  - ws-server-deployment.yaml
  - ws-server-service.yaml
  - web-server-deployment.yaml
  - web-server-service.yaml
  - ingress.yaml

images:
  - name: omnom62/xpilot-webnet
    newTag: latest # CI overwrites this with the git SHA before applying
